"""empty message

Revision ID: 16b3433077ac
Revises: cb28bf60a898
Create Date: 2019-11-25 22:25:27.073909

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '16b3433077ac'
down_revision = 'cb28bf60a898'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comments', sa.Column('level', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('comments', 'level')
    # ### end Alembic commands ###
