"""empty message

Revision ID: 30653857db2c
Revises: 4e0d49c3d727
Create Date: 2019-11-16 01:08:00.999112

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '30653857db2c'
down_revision = '4e0d49c3d727'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('mobile', sa.String(length=64), nullable=True))
    op.drop_index('ix_users_email', table_name='users')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_users_email', 'users', ['email'], unique=1)
    op.drop_column('users', 'mobile')
    # ### end Alembic commands ###
