"""empty message

Revision ID: 43892a53b978
Revises: 9421c84b8d2b
Create Date: 2019-11-24 17:05:56.465494

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '43892a53b978'
down_revision = '9421c84b8d2b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('categories', sa.Column('enable', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('categories', 'enable')
    # ### end Alembic commands ###
