"""empty message

Revision ID: 45262aca9d61
Revises: 079a6ead44b9
Create Date: 2019-11-25 01:30:15.476419

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '45262aca9d61'
down_revision = '079a6ead44b9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('categories', sa.Column('public', sa.Boolean(), nullable=True))
    op.add_column('posts', sa.Column('enable', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('posts', 'enable')
    op.drop_column('categories', 'public')
    # ### end Alembic commands ###
