"""empty message

Revision ID: 53a56bc5304a
Revises: bdca5a738329
Create Date: 2020-04-28 19:49:21.616268

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '53a56bc5304a'
down_revision = 'bdca5a738329'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('categories', sa.Column('top_parent_id', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('categories', 'top_parent_id')
    # ### end Alembic commands ###
