"""empty message

Revision ID: 59d12db62038
Revises: d9d88a260422
Create Date: 2020-04-26 00:26:39.259344

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '59d12db62038'
down_revision = 'd9d88a260422'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comments', sa.Column('temp_contact_type', sa.Integer(), nullable=True))
    op.add_column('comments', sa.Column('temp_contact_value', sa.String(length=64), nullable=True))
    op.add_column('comments', sa.Column('temp_name', sa.String(length=64), nullable=True))
    op.create_unique_constraint(None, 'comments', ['temp_contact_value'])
    op.create_unique_constraint(None, 'comments', ['temp_name'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'comments', type_='unique')
    op.drop_constraint(None, 'comments', type_='unique')
    op.drop_column('comments', 'temp_name')
    op.drop_column('comments', 'temp_contact_value')
    op.drop_column('comments', 'temp_contact_type')
    # ### end Alembic commands ###
