"""empty message

Revision ID: 9421c84b8d2b
Revises: 3858c9649935
Create Date: 2019-11-24 16:29:15.617550

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9421c84b8d2b'
down_revision = '3858c9649935'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_categories_name'), 'categories', ['name'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_categories_name'), table_name='categories')
    # ### end Alembic commands ###
