"""empty message

Revision ID: abc52e39d615
Revises: 711d94545a1f
Create Date: 2019-11-16 12:30:41.965300

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'abc52e39d615'
down_revision = '711d94545a1f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('captchas', sa.Column('timestamp', sa.DateTime(), nullable=True))
    op.create_index(op.f('ix_captchas_timestamp'), 'captchas', ['timestamp'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_captchas_timestamp'), table_name='captchas')
    op.drop_column('captchas', 'timestamp')
    # ### end Alembic commands ###
